### ISSUE TITLE
Website is run on insecure HTTP

### ISSUE THREAD

**Issue by code-syl** [johnpieroni89/vendorholonet#1]
The website deals with access tokens and potentionally in-character sensitive information like galaxy coordinates. However, is it run without an HTTPS certificate.

Furthermore, it requests resources from the SWCombine WS2.0 endpoints on insecure HTTP endpoints. As far as I can tell, SWCombine does not automatically upgrade requests made to HTTP endpoints to HTTPS.
![image](https://user-images.githubusercontent.com/93523097/213444772-5571456a-cb25-42e8-9431-78c6ec648c72.png)

It could be a valuable upgrade to use HTTPS.

**Comment by johnpieroni89** [comment]
refactored code to prioritize https
